### ISSUE TITLE
Encountered the issue "trained model cannot be opened"

### ISSUE THREAD

**Issue by adamliuio** [vendi12/MemN2N-tableQA#1]
Hi there,

When I was trying to run the demo on my computer with the command "python -m demo.qa", I encountered the error as below:

*******************************

Loading word embeddings model
Traceback (most recent call last):
  File "/Users/AdamLiu/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/AdamLiu/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/AdamLiu/Downloads/test/MemN2N-tableQA3/demo/qa.py", line 445, in <module>
    run_web_demo(args.data_dir, args.model_file)
  File "/Users/AdamLiu/Downloads/test/MemN2N-tableQA3/demo/qa.py", line 417, in run_web_demo
    webapp.init(data_dir, model_file)
  File "/Users/AdamLiu/Downloads/test/MemN2N-tableQA3/demo/web/webapp.py", line 21, in init
    memn2n = MemN2N(data_dir, model_file)
  File "/Users/AdamLiu/Downloads/test/MemN2N-tableQA3/demo/qa.py", line 44, in __init__
    self.word_model = fasttext.load_model(EMBEDDINGS_MODEL_PATH)
  File "fasttext/fasttext.pyx", line 146, in fasttext.fasttext.load_model (fasttext/fasttext.cpp:4128)
ValueError: fastText: trained model cannot be opened!

*******************************

Do you mind share the solution for this one? Thanks a lot.

**Comment by svakulenk0** [comment]
Hi! Is it solved already?)

**Comment by adamliuio** [comment]
@vendi12 unfortunately not. I was trying to use fasttext, and after following the instructions still can not get it done right and get the demo up and running. Still trying.

Do you mind give more specific instructions on how did you put all the things to work? that might be very helpful.

Thanks.

**Comment by svakulenk0** [comment]
Ah sorry! I thought it's resolved. 

You need to build the fastext model yourself because it is too big to upload on Github. 

Here are more detailed instructions: 
1. clone fastText Github repository (git clone https://github.com/facebookresearch/fastText.git)
2. run ./word-vector-example.sh to train a model on the English Wikipedia
3. copy the trained mode to the MemN2N-tableQA project folder: embeddings/fil9.bin

Please let me know if that works!
SV
