### ISSUE TITLE
Getting error when dealing with numbers from data txt files.

### ISSUE THREAD

**Issue by adamliuio** [vendi12/MemN2N-tableQA#3]
Hi @vendi12 ,

So I was not able to use fasttext.py to load the FastText model, as an alternative I chose Gensim to load it, however, seems like the numbers from data txt files could not be dealt with. For example, in this case, it is the number 41010.

I replaced the loading part of code as below:

```
from gensim.models.wrappers import FastText
self.word_model = FastText.load_fasttext_format(EMBEDDINGS_MODEL_PATH)
```

However, when the program executed to the part below:

```
print("Embedding dictionary words")
for word in memn2n.general_config.dictionary.keys():
    memn2n.dict_vectors[word] = memn2n.word_model[word]
```

I got the error below:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 453, in <module>
    run_web_demo(args.data_dir, args.model_file)
  File "/home/ubuntu/BI_AI/MemN2N-tableQA/demo/qa.py", line 425, in run_web_demo
    webapp.init(data_dir, model_file)
  File "demo/web/webapp.py", line 28, in init
    memn2n.dict_vectors[word] = memn2n.word_model[word]
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/word2vec.py", line 1281, in __getitem__
    return self.wv.__getitem__(words)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/keyedvectors.py", line 589, in __getitem__
    return self.word_vec(words)
  File "/usr/local/lib/python2.7/dist-packages/gensim/models/wrappers/fasttext.py", line 94, in word_vec
    raise KeyError('all ngrams for word %s absent from model' % word)
KeyError: 'all ngrams for word 41010 absent from model'
```

I tried every possible approach I could find and came up with, but couldn't find anything.

Can you share what version or some information about fasttext.py you are using for this task?

Thanks.

**Comment by svakulenk0** [comment]
Hi! Sorry for the late reply! I am using https://pypi.python.org/pypi/fasttext "It requires Cython in order to build the C++ extension" Did not try replacing it with gensim there may be some hiccups there I assume.

**Comment by adamliuio** [comment]
Yeah, fasttext.py somehow doesn't work. In the issues page it was discussed, seems like it was because of the version of fasttext is newer.

Switched to use pyfasttext, working fine now.
